steps:
- name: gcr.io/cloud-builders/gcloud
  args: [
    'functions',
    'deploy',
    'HelloPubSub',
    '--runtime',
    'go111',
    '--trigger-topic',
    '${_FUNCTIONS_TOPIC}',
    '--source',
    'https://source.developers.google.com/projects/${_PROJECT_ID}/repos/${_REPO_NAME}/moveable-aliases/${_BRANCH_NAME}/paths/hello'
  ]
